### ISSUE TITLE
请求测试，某些网站在用户登录后再进行diy会显示访问400等错误

### ISSUE THREAD

**Issue by riddle911** [speed/feeddiy#1]
作者老哥，feed43用起来不稳定。
你的站物美价廉，准备充值。
但是测试发现个问题，不知道你能不能重现。

http://www.gssl.gov.cn/slzx/tzdt/sslsdgcymglj/
http://www.gzsskhstymj.gov.cn/channels/9768.html
http://www.scfpym.gov.cn/list.aspx?cid=131

以上两个网站访问在你页面里访问均400，你的网站在不登录情况下有几率400，登录后再访问就100% 400

请老哥抽空看看能否解决。谢谢了~

**Comment by speed** [comment]
@riddle911 我这边没有重现，你可以在后台切换爬虫集群试试

**Comment by speed** [comment]
@riddle911 
配好了这个，这个网站的csspath需要手动做些修改，如果有提取不了的你可以留言我帮你配置，你可以clone
http://www.gssl.gov.cn/slzx/tzdt/sslsdgcymglj/
http://www.feeddiy.com/feed/7Fra2e

**Comment by speed** [comment]
@riddle911 你是不是选择了china vps , 刚刚想重现问题发现服务器不能访问国内ip，我得跟服务商沟通下，你可以先选择其它集群

**Comment by riddle911** [comment]
报告老哥- -cluster我昨天没有动过默认gae，刚刚试着来回切换了下，回到gae，貌似能正常访问了。
问题比较玄学，昨天在几个浏览器都测试了。
我接下来继续测试用下 谢谢！
