### ISSUE TITLE
I want to change my account email

### ISSUE THREAD

**Issue by denastria** [speed/feeddiy#5]
How to operate? :-(

**Comment by speed** [comment]
You can re-register an account, I will do data migration for you.

**Comment by denastria** [comment]
Thank U, but I've changed my mind.
________________________________
发件人: speed <notifications@github.com>
发送时间: 2018年11月7日 16:52
收件人: speed/feeddiy
抄送: VERNON-YU; Author
主题: Re: [speed/feeddiy] I want to change my account email (#5)


You can re-register an account, I will do data migration for you.
